ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] HTTP GET /acme-jobs/META-INF/views/framework/page.jsp HTTP/1.1
ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] Status: 500
ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] Exception: org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:373): bound must be greater than origin; nested exception is java.lang.IllegalArgumentException: bound must be greater than origin
java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:378): bound must be greater than origin
ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] HTTP GET /acme-jobs/META-INF/views/framework/page.jsp HTTP/1.1
ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] Status: 500
ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] Exception: org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:373): bound must be greater than origin; nested exception is java.lang.IllegalArgumentException: bound must be greater than origin
java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:378): bound must be greater than origin
ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] HTTP GET /acme-jobs/META-INF/views/framework/page.jsp HTTP/1.1
ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] Status: 500
ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] Exception: org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:373): bound must be greater than origin; nested exception is java.lang.IllegalArgumentException: bound must be greater than origin
java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:378): bound must be greater than origin
ERROR [com.zaxxer.hikari.pool.HikariPool] at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174): Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method): Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method): Connection refused: connect
WARN [org.springframework.boot.autoconfigure.orm.jpa.DatabaseLookup] at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:328): Could not get Connection for extracting meta-data; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81): Failed to obtain JDBC Connection; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174): Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method): Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method): Connection refused: connect
ERROR [com.zaxxer.hikari.pool.HikariPool] at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174): Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method): Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method): Connection refused: connect
WARN [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] HHH000342: Could not obtain connection to query metadata : Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
WARN [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
ERROR [org.springframework.boot.SpringApplication] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778): Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:275): Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:100): Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
ERROR [org.apache.catalina.util.LifecycleBase] at org.apache.catalina.connector.Connector.startInternal(Connector.java:1008): Protocol handler start failed
at sun.nio.ch.Net.bind0(Native Method): Address already in use: bind
ERROR [org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter] ***************************
APPLICATION FAILED TO START
***************************
Description:
The Tomcat connector configured to listen on port 8080 failed to start. The port may already be in use or the connector may be misconfigured.
Action:
Verify the connector's configuration, identify and stop any process that's listening on port 8080, or configure this application to listen on another port.
ERROR [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/acme-jobs].[jsp]] at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source): d != java.lang.String
ERROR [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/acme-jobs].[jsp]] at org.apache.tiles.request.servlet.ServletUtil.wrapServletException(ServletUtil.java:61): JSPException including path '../authenticated/user-account/form.jsp'.
at org.apache.jsp.tag.web.print_tag.doTag(print_tag.java:168): org.springframework.core.convert.ConversionFailedException: Failed to convert from type [acme.datatypes.Phone] to type [java.lang.String] for value '<<+1 (234) 567890>>'; nested exception is java.util.IllegalFormatConversionException: d != java.lang.String
at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47): Failed to convert from type [acme.datatypes.Phone] to type [java.lang.String] for value '<<+1 (234) 567890>>'; nested exception is java.util.IllegalFormatConversionException: d != java.lang.String
at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source): d != java.lang.String
ERROR [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/acme-jobs].[dispatcherServlet]] at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source): d != java.lang.String
ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] HTTP GET /acme-jobs/master/panic HTTP/1.1
ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] Status: 500
ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] Exception: org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1013): Request processing failed; nested exception is org.apache.tiles.request.render.CannotRenderException: JSPException including path '../authenticated/user-account/form.jsp'.
org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:399): JSPException including path '../authenticated/user-account/form.jsp'.
org.apache.tiles.request.servlet.ServletUtil.wrapServletException(ServletUtil.java:61): JSPException including path '../authenticated/user-account/form.jsp'.
org.apache.jsp.tag.web.print_tag.doTag(print_tag.java:168): org.springframework.core.convert.ConversionFailedException: Failed to convert from type [acme.datatypes.Phone] to type [java.lang.String] for value '<<+1 (234) 567890>>'; nested exception is java.util.IllegalFormatConversionException: d != java.lang.String
org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47): Failed to convert from type [acme.datatypes.Phone] to type [java.lang.String] for value '<<+1 (234) 567890>>'; nested exception is java.util.IllegalFormatConversionException: d != java.lang.String
java.util.Formatter$FormatSpecifier.failConversion(Unknown Source): d != java.lang.String
ERROR [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/acme-jobs].[jsp]] at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source): d != java.lang.String
ERROR [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/acme-jobs].[jsp]] at org.apache.tiles.request.servlet.ServletUtil.wrapServletException(ServletUtil.java:61): JSPException including path '../authenticated/user-account/form.jsp'.
at org.apache.jsp.tag.web.print_tag.doTag(print_tag.java:168): org.springframework.core.convert.ConversionFailedException: Failed to convert from type [acme.datatypes.Phone] to type [java.lang.String] for value '<<+1 (234) 567890>>'; nested exception is java.util.IllegalFormatConversionException: d != java.lang.String
at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47): Failed to convert from type [acme.datatypes.Phone] to type [java.lang.String] for value '<<+1 (234) 567890>>'; nested exception is java.util.IllegalFormatConversionException: d != java.lang.String
at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source): d != java.lang.String
ERROR [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/acme-jobs].[dispatcherServlet]] at java.util.Formatter$FormatSpecifier.failConversion(Unknown Source): d != java.lang.String
ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] HTTP GET /acme-jobs/master/panic HTTP/1.1
ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] Status: 500
ERROR [org.apache.jsp.META_002dINF.views.framework.panic_jsp] Exception: org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1013): Request processing failed; nested exception is org.apache.tiles.request.render.CannotRenderException: JSPException including path '../authenticated/user-account/form.jsp'.
org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:399): JSPException including path '../authenticated/user-account/form.jsp'.
org.apache.tiles.request.servlet.ServletUtil.wrapServletException(ServletUtil.java:61): JSPException including path '../authenticated/user-account/form.jsp'.
org.apache.jsp.tag.web.print_tag.doTag(print_tag.java:168): org.springframework.core.convert.ConversionFailedException: Failed to convert from type [acme.datatypes.Phone] to type [java.lang.String] for value '<<+1 (234) 567890>>'; nested exception is java.util.IllegalFormatConversionException: d != java.lang.String
org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47): Failed to convert from type [acme.datatypes.Phone] to type [java.lang.String] for value '<<+1 (234) 567890>>'; nested exception is java.util.IllegalFormatConversionException: d != java.lang.String
java.util.Formatter$FormatSpecifier.failConversion(Unknown Source): d != java.lang.String
